[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@analog-gmp=lib/analog-gmp/src/', '@solmate=lib/solmate/src/', '@ERC721A/contracts=lib/ERC721A/contracts']
ffi = false

# Solc Options
solc = '0.8.25'
optimizer = true
optimizer_runs = 200000

# EVM Options
gas_limit = 30000000
gas_price = 1
block_base_fee_per_gas = 0
block_gas_limit = 30000000
